//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectionType
    {
        public int Id { get; set; }
        public short DirectionId { get; set; }
        public string Description { get; set; }
    
        public virtual Direction Direction { get; set; }
    }
}
