//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public long Id { get; set; }
        public System.DateTimeOffset ActivityTime { get; set; }
        public int ProductId { get; set; }
        public int SourceLocationId { get; set; }
        public int DestinationLocationId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Location DestinationLocation { get; set; }
        public virtual Location SourceLocation { get; set; }
        public virtual Product Product { get; set; }
    }
}
