//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public long Id { get; set; }
        public System.DateTimeOffset ActivityTime { get; set; }
        public int ProductId { get; set; }
        public int LocationId { get; set; }
        public Nullable<short> DirectionId { get; set; }
        public int OriginalQuantity { get; set; }
        public int NewQuantity { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Location Location { get; set; }
        public virtual Product Product { get; set; }
    }
}
